export const IMGS_OF_BEFORE = [
  './img/before/b_00.webp',
  './img/before/b_01.webp',
  './img/before/b_02.webp',
  './img/before/b_03.webp',
  './img/before/b_04.webp',
  './img/before/b_05.webp',
  './img/before/b_06.webp',
  './img/before/b_07.webp',
]

export const IMGS_OF_AFTER = [
  './img/after/a_00.webp',
  './img/after/a_01.webp',
  './img/after/a_02.webp',
  './img/after/a_03.webp',
  './img/after/a_04.webp',
  './img/after/a_05.webp',
  './img/after/a_06.webp',
  './img/after/a_07.webp',
  './img/after/a_08.webp',
  './img/after/a_09.webp',
  './img/after/a_10.webp',
  './img/after/a_11.webp',
  './img/after/a_12.webp',
  './img/after/a_13.webp',
]

export const IMGS_OF_FIRST = [
  './img/first/f_00.webp',
  './img/first/f_01.webp',
  './img/first/f_02.webp',
  './img/first/f_03.webp',
  './img/first/f_04.webp',
  './img/first/f_05.webp',
  './img/first/f_06.webp',
  './img/first/f_07.webp',
  './img/first/f_08.webp',
  './img/first/f_09.webp',
  './img/first/f_10.webp',
  './img/first/f_11.webp',
  './img/first/f_12.webp',
  './img/first/f_13.webp',
  './img/first/f_14.webp',
  './img/first/f_15.webp',
  './img/first/f_16.webp',
  './img/first/f_17.webp',
  './img/first/f_18.webp',
]

export const IMGS_OF_SECOND = [
  './img/second/s_00.webp',
  './img/second/s_01.webp',
  './img/second/s_02.webp',
  './img/second/s_03.webp',
  './img/second/s_04.webp',
  './img/second/s_05.webp',
  './img/second/s_06.webp',
  './img/second/s_07.webp',
]